# Generated by git-drift's release workflow (scripts/formula.mjs). Do not edit by hand.
class GitDrift < Formula
  desc "Find code that never made it to GitHub, on your laptop and your servers"
  homepage "https://github.com/chiefsmurph/git-drift"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.3.0/git-drift-darwin-arm64.tar.gz"
      sha256 "8dde66fb7b0b8896f7e53a72922cd40621731d378c019b7e01b150aecfdcdd86"
    end
    on_intel do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.3.0/git-drift-darwin-x64.tar.gz"
      sha256 "71b09f2e3450cfbaf428aa06ef0959b725095f3eed981c1aeb4c8c9c96eaa441"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.3.0/git-drift-linux-arm64.tar.gz"
      sha256 "02232fff5c09dc3298edc46fce19e86661ebe14f2a2cb6d6266bf90c2cd76b9a"
    end
    on_intel do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.3.0/git-drift-linux-x64.tar.gz"
      sha256 "9ede0391a66e9c7dca013d2de6c3afd800653da15742f2953e8f920cec98ebc2"
    end
  end

  def install
    bin.install "git-drift"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-drift --version")
  end
end
