# Generated by git-drift's release workflow (scripts/formula.mjs). Do not edit by hand.
class GitDrift < Formula
  desc "Find code that never made it to GitHub, on your laptop and your servers"
  homepage "https://github.com/chiefsmurph/git-drift"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.4.1/git-drift-darwin-arm64.tar.gz"
      sha256 "167bff1609957d213e047681b5bf631a4e3b76f4b33c9e31a217184923716479"
    end
    on_intel do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.4.1/git-drift-darwin-x64.tar.gz"
      sha256 "25a03b3f47e8a42f4348e422436ab1389b8d23a553319ece894c660409d5dee0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.4.1/git-drift-linux-arm64.tar.gz"
      sha256 "a0682a1d1aa6d706330917845a9772b7c951a0960bcf594cc512b7136556a705"
    end
    on_intel do
      url "https://github.com/chiefsmurph/git-drift/releases/download/v0.4.1/git-drift-linux-x64.tar.gz"
      sha256 "9353665f4bbee29317a2fe5a69d43c37fc4fdeebdce89e9210196d78e6838b98"
    end
  end

  def install
    bin.install "git-drift"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-drift --version")
  end
end
