# Generated by pingpigeon-cli's release workflow (scripts/formula.mjs). Do not edit by hand.
class Pingpigeon < Formula
  desc "Email, push and text yourself from the terminal"
  homepage "https://pingpigeon.app"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.0/pingpigeon-darwin-arm64.tar.gz"
      sha256 "008ecd2979ba624c495dd212508276208bd1bc500a0523fa248019cb03fde682"
    end
    on_intel do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.0/pingpigeon-darwin-x64.tar.gz"
      sha256 "a9ceeb41a6c35ac2ca29508c98745c9b3eabe7519f3991474d26553bb16edea1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.0/pingpigeon-linux-arm64.tar.gz"
      sha256 "6f9b54cd075461f3576dab3d947822ba6582de58e6be40242fc1d82ed52d7575"
    end
    on_intel do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.0/pingpigeon-linux-x64.tar.gz"
      sha256 "51119f0026dc35ab88e892de4ce9d8375614ddfc40ce1a1de8b3a8a38ed3c43e"
    end
  end

  def install
    bin.install "pingpigeon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pingpigeon --version")
  end
end
