# Generated by pingpigeon-cli's release workflow (scripts/formula.mjs). Do not edit by hand.
class Pingpigeon < Formula
  desc "Email, push and text yourself from the terminal"
  homepage "https://pingpigeon.app"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.1/pingpigeon-darwin-arm64.tar.gz"
      sha256 "a39484d0b78ff674b79a48a12427c2b6a451787c6500c427413c32e67ee047d8"
    end
    on_intel do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.1/pingpigeon-darwin-x64.tar.gz"
      sha256 "bf97cb85935a3f1e31466357b30976514b12b811647fc1f0ec3af7c141387260"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.1/pingpigeon-linux-arm64.tar.gz"
      sha256 "b4647d5934305772abd1b0b312d6b051a549b763ed53eb6bc3f430feb0807c18"
    end
    on_intel do
      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v0.1.1/pingpigeon-linux-x64.tar.gz"
      sha256 "8f9625b58e2d6e1a18078c49bc13b7b307a644fbaf03a78feed4d5df48cacc44"
    end
  end

  def install
    bin.install "pingpigeon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pingpigeon --version")
  end
end
